server:
  port: ${APP_PORT:9444}
  tomcat:
    connection-timeout: 120000

spring:
  application:
    name: bank-core-service
  datasource:
    url: ${USER_DATABASE_URL:jdbc:postgresql://localhost:5432/bank}
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
      group-id: bank-group
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    liquibase.changelog: DEBUG