spring:
  application:
    name: user_service
  datasource:
    url: ${USER_DATABASE_URL:jdbc:postgresql://localhost:5433/users}
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:kafka:9092}
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1ad1f123a9d2b5f8e3a9c8b5f6v8a3d9
  accessToken:
    expirationMillis: 3600000 # 1hr
  refreshToken:
    expirationMillis: 2592000000 # 30d

server:
  port: ${APP_PORT:9447}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true