spring:
  cloud:
    gateway:
      routes:
        - id: bank-credit-service
          uri: http://localhost:8989
          predicates:
            - Path=/credit/**
        - id: bank-core-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: bank-users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

server:
  port: 8581

jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1ad1f123a9d2b5f8e3a9c8b5f6v8a3d9
